In [1]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import pickle
import numpy as np

In [2]:
data=pd.read_csv("dataset.csv",sep=",")
data

day  month  year  Temperature   RH   Ws  Rain   FFMC   DMC    DC  ISI  \
0      1      6  2012           29   57   18    0.0  65.7   3.4   7.6  1.3   
1      2      6  2012           29   61   13    1.3  64.4   4.1   7.6  1.0   
2      3      6  2012           26   82   22   13.1  47.1   2.5   7.1  0.3   
3      4      6  2012           25   89   13    2.5  28.6   1.3   6.9  0.0   
4      5      6  2012           27   77   16    0.0  64.8   3.0  14.2  1.2   
..   ...    ...   ...          ...  ...  ...    ...   ...   ...   ...  ...   
239   26      9  2012           30   65   14    0.0  85.4  16.0  44.5  4.5   
240   27      9  2012           28   87   15    4.4  41.1   6.5   8.0  0.1   
241   28      9  2012           27   87   29    0.5  45.9   3.5   7.9  0.4   
242   29      9  2012           24   54   18    0.1  79.7   4.3  15.2  1.7   
243   30      9  2012           24   64   15    0.2  67.3   3.8  16.5  1.2   

      BUI  FWI     Classes    
0     3.4  0.5   not fire     
1     3.9  0.4   not fire     
2     2.7  0.1   not fire     
3     1.7  0.0   not fire     
4     3.9  0.5   not fire     
..    ...  ...           ...  
239  16.9  6.5       fire     
240   6.2  0.0   not fire     
241   3.4  0.2   not fire     
242   5.1  0.7   not fire     
243   4.8  0.5  not fire      

[244 rows x 14 columns]

In [3]:
X = data.drop('year', axis=1)
X=data.iloc[:,:12].values
Y=data.iloc[:,13:].values

In [4]:
X

array([[1.000e+00, 6.000e+00, 2.012e+03, ..., 7.600e+00, 1.300e+00,
        3.400e+00],
       [2.000e+00, 6.000e+00, 2.012e+03, ..., 7.600e+00, 1.000e+00,
        3.900e+00],
       [3.000e+00, 6.000e+00, 2.012e+03, ..., 7.100e+00, 3.000e-01,
        2.700e+00],
       ...,
       [2.800e+01, 9.000e+00, 2.012e+03, ..., 7.900e+00, 4.000e-01,
        3.400e+00],
       [2.900e+01, 9.000e+00, 2.012e+03, ..., 1.520e+01, 1.700e+00,
        5.100e+00],
       [3.000e+01, 9.000e+00, 2.012e+03, ..., 1.650e+01, 1.200e+00,
        4.800e+00]])

In [5]:
Y

array([['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['fire   '],
       ['fire   '],
       ['fire   '],
       ['not fire   '],
       ['not fire   '],
       ['fire   '],
       ['fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['fire   '],
       ['not fire   '],
       ['fire   '],
       ['fire   '],
       ['fire   '],
       ['fire   '],
       ['fire   '],
       ['fire   '],
       ['not fire   '],
       ['fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['fire   '],
       ['fire   '],
       ['not fire   '],
       ['fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       ['not fire   '],
       [

In [6]:
Y = Y.astype(str)
Y = np.char.strip(Y, chars=None)

In [7]:
Y = np.where(Y == 'fire', 0, 1)

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout



In [9]:
X = X.astype(float)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
y_train

array([[0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
    

In [36]:
model = Sequential()
model.add(Dense(12, input_shape=(12,), activation='relu'))
model.add(Dense(units = 42, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 126, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dropout(0.3))
model.add(Dense(units = 32, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 8, kernel_initializer = 'uniform', activation = 'relu'))
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train.ravel(), batch_size = 4, epochs = 100, validation_split=0.2)
model.save('resources/algerie.h5')

Epoch 1/100
39/39 [==============================] - 2s 6ms/step - loss: 0.6931 - accuracy: 0.5192 - val_loss: 0.6925 - val_accuracy: 0.7436
Epoch 2/100
39/39 [==============================] - 0s 2ms/step - loss: 0.6695 - accuracy: 0.8013 - val_loss: 0.6455 - val_accuracy: 0.8974
Epoch 3/100
39/39 [==============================] - 0s 3ms/step - loss: 0.5356 - accuracy: 0.8654 - val_loss: 0.5930 - val_accuracy: 0.9231
Epoch 4/100
39/39 [==============================] - 0s 2ms/step - loss: 0.4729 - accuracy: 0.9423 - val_loss: 0.5550 - val_accuracy: 0.9487
Epoch 5/100
39/39 [==============================] - 0s 3ms/step - loss: 0.4391 - accuracy: 0.9359 - val_loss: 0.5263 - val_accuracy: 0.9487
Epoch 6/100
39/39 [==============================] - 0s 3ms/step - loss: 0.4302 - accuracy: 0.9487 - val_loss: 0.5086 - val_accuracy: 0.9744
Epoch 7/100
39/39 [==============================] - 0s 2ms/step - loss: 0.3387 - accuracy: 0.9615 - val_loss: 0.2024 - val_accuracy: 0.9744
Epoch 8/100
3

In [29]:
import joblib
joblib.dump(sc, 'resources/scaler.pkl')

['resources/scaler.pkl']

In [30]:
import numpy as np
from keras.models import load_model
import joblib


sc = joblib.load('resources/scaler.pkl')
model = load_model('resources/algerie.h5')

#day	month	Temperature	RH	Ws	Rain	FFMC	DMC	DC	ISI	BUI	FWI
data_pred = sc.transform(np.array([[23,8,56,6,14,0,9,9.4,115.6,7.5,36,15.2],[1, 8, 120,71,14,6.5,64.5,3.3,90.1,1,30.5,0.4],[6,8,31,67,14,0,82.6,5.8,22.2,3.1,7,2.5]]))
pred = model.predict(data_pred)
pred = np.where(pred > 0.5, "Fire", "No Fire")
print(pred)


1/1 [==============================] - 0s 151ms/step
[['No Fire']
 ['No Fire']
 ['No Fire']]


In [32]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
knn = KNeighborsClassifier(n_neighbors=2)

knn.fit(X_train, y_train.ravel())

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

Accuracy: 93.88%


In [33]:
data_pred = sc.transform(np.array([[23,8,35,56,14,0,89,29.4,115.6,7.5,36,15.2],[1, 8, 120,71,14,6.5,64.5,3.3,90.1,1,30.5,0.4],[6,8,31,67,14,0,82.6,5.8,22.2,3.1,7,2.5]]))

#data_pred = sc.transform(np.array([]))
preds = knn.predict(data_pred)
print(preds)
print( ['No Fire' if label == 1 else 'Fire' for label in preds])

[1 1 1]
['No Fire', 'No Fire', 'No Fire']
